import { StyleSheet } from 'react-native';

import { colors } from '../../../theme/colors';
import { radius } from '../../../theme/radius';
import { spacing } from '../../../theme/spacing';

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#FFFFFF' },
  kav: { flex: 1 },
  keyboardBg: { position: 'absolute', bottom: 0, left: 0, right: 0, height: 300, backgroundColor: '#FFFFFF' },
  layout: { flex: 1, justifyContent: 'flex-end' },
  hero: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    paddingTop: 52,
    paddingHorizontal: spacing.xl,
    paddingBottom: spacing.xl,
  },
  backBtn: {
    marginBottom: spacing.xl,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(15,23,42,0.42)',
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.18)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headlineBlock: { gap: 4, marginTop: spacing.sm },
  h1: {
    fontFamily: 'Inter_700Bold',
    fontSize: 52,
    lineHeight: 54,
    color: '#FFFFFF',
    letterSpacing: -2.3,
  },
  h2Row: { flexDirection: 'row', alignItems: 'baseline' },
  strokeWrap: { position: 'relative' },
  h2StrokeBase: {
    fontFamily: 'Inter_700Bold',
    fontSize: 52,
    lineHeight: 58,
    letterSpacing: -2.3,
  },
  h2StrokeOutline: {
    color: '#FFFFFF',
    textShadowColor: 'rgba(255,255,255,0.18)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 4,
  },
  h2StrokeFill: {
    position: 'absolute',
    top: 0,
    left: 0,
    color: '#020617',
  },
  h2Solid: {
    fontFamily: 'Inter_700Bold',
    fontSize: 52,
    lineHeight: 58,
    color: '#FFFFFF',
    letterSpacing: -2.3,
  },
  h3Accent: {
    fontFamily: 'Inter_700Bold',
    fontSize: 28,
    lineHeight: 34,
    color: '#DBEAFE',
    letterSpacing: -0.7,
    marginTop: 4,
  },
  sheet: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    paddingTop: 18,
    maxHeight: '70%',
    borderTopWidth: 1,
    borderColor: 'rgba(96,165,250,0.18)',
    shadowColor: '#1D4ED8',
    shadowOffset: { width: 0, height: -6 },
    shadowOpacity: 0.16,
    shadowRadius: 20,
    elevation: 20,
  },
  handle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#1E3A8A',
    alignSelf: 'center',
    marginBottom: 4,
  },
  sheetScroll: {
    paddingHorizontal: spacing.xl,
    paddingTop: 8,
    paddingBottom: 36,
  },
  sheetHead: {
    marginBottom: 16,
  },
  sheetHeadCopy: { flex: 1 },
  sparkleCircle: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: '#EFF6FF',
    borderWidth: 1.5,
    borderColor: '#BFDBFE',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sheetTitle: {
    fontFamily: 'Inter_700Bold',
    fontSize: 26,
    color: '#0F172A',
    letterSpacing: -0.7,
    lineHeight: 30,
  },
  sheetSub: {
    fontFamily: 'Inter_400Regular',
    fontSize: 16,
    color: '#64748B',
    lineHeight: 22,
    marginTop: 6,
  },
  errorBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    backgroundColor: '#FEF2F2',
    borderWidth: 1,
    borderColor: '#FECACA',
    borderRadius: radius.md,
    padding: spacing.md,
    marginBottom: spacing.md,
  },
  errorBannerText: {
    fontFamily: 'Inter_400Regular',
    fontSize: 13,
    color: colors.error,
    flex: 1,
    lineHeight: 19,
  },
  form: { marginBottom: spacing.md },
  fieldWrap: { gap: 7 },
  fieldGap: { marginTop: spacing.md },
  fieldLabel: {
    fontFamily: 'Inter_600SemiBold',
    fontSize: 14,
    color: '#334155',
    letterSpacing: 0.1,
  },
  inputShell: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    borderWidth: 1.5,
    borderColor: '#E2E8F0',
    borderRadius: radius.md,
    minHeight: 56,
    paddingRight: spacing.md,
    overflow: 'hidden',
  },
  inputError: { borderColor: colors.error, backgroundColor: '#FFF5F5' },
  inputIcon: {
    width: 50,
    alignItems: 'center',
    justifyContent: 'center',
    borderRightWidth: 1,
    borderRightColor: '#E2E8F0',
    height: 56,
  },
  inputIconError: { borderRightColor: '#FECACA', backgroundColor: '#FFF0F0' },
  input: {
    flex: 1,
    fontFamily: 'Inter_400Regular',
    fontSize: 16,
    color: '#0F172A',
    paddingHorizontal: spacing.md,
    minHeight: 54,
  },
  validIcon: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#0F172A',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 2,
  },
  eyeBtn: { padding: 4 },
  fieldError: { fontFamily: 'Inter_400Regular', fontSize: 12, color: '#FCA5A5' },
  strengthWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    marginTop: 6,
  },
  strengthBars: { flexDirection: 'row', gap: 5, flex: 1 },
  strengthBar: { flex: 1, height: 4, borderRadius: 2 },
  strengthLabel: {
    fontFamily: 'Inter_600SemiBold',
    fontSize: 12,
    width: 44,
    textAlign: 'right',
  },
  termsText: {
    fontFamily: 'Inter_400Regular',
    fontSize: 12,
    color: '#64748B',
    lineHeight: 18,
    textAlign: 'center',
    marginBottom: spacing.md,
  },
  termsLink: { fontFamily: 'Inter_600SemiBold', color: '#0F172A' },
  btnPrimary: { borderRadius: radius.md, overflow: 'hidden', marginBottom: spacing.md },
  btnFill: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 56,
    gap: spacing.sm,
    paddingHorizontal: spacing.xl,
    backgroundColor: '#0f172a',
  },
  btnLabel: {
    fontFamily: 'Inter_700Bold',
    fontSize: 17,
    color: '#FFFFFF',
    letterSpacing: 0.3,
  },
  btnArrow: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: 'rgba(239,246,255,0.95)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dotsRow: { flexDirection: 'row', gap: 5, marginRight: 6 },
  dot: { width: 6, height: 6, borderRadius: 3, backgroundColor: 'rgba(255,255,255,0.55)' },
  orRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    marginBottom: spacing.md,
  },
  orLine: { flex: 1, height: 1, backgroundColor: 'rgba(96,165,250,0.14)' },
  orText: { fontFamily: 'Inter_400Regular', fontSize: 13, color: '#94A3B8' },
  signinBtn: { flexDirection: 'row', justifyContent: 'center', paddingVertical: 4 },
  signinText: { fontFamily: 'Inter_400Regular', fontSize: 14, color: '#64748B' },
  signinLink: { fontFamily: 'Inter_700Bold', fontSize: 14, color: '#0F172A' },
});
