import { StyleSheet } from 'react-native';

import { colors } from '../../../theme/colors';
import { radius } from '../../../theme/radius';
import { spacing } from '../../../theme/spacing';

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#020617' },
  scroll: { flexGrow: 1 },
  hero: {
    alignItems: 'center',
    paddingTop: 46,
    paddingHorizontal: spacing.xl,
    paddingBottom: 28,
  },
  heroHeader: {
    alignItems: 'center',
    width: '100%',
    marginBottom: 24,
  },
  heroEyebrow: {
    fontFamily: 'Inter_600SemiBold',
    fontSize: 13,
    color: '#E0F2FE',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  settingsBtn: {
    position: 'absolute',
    right: 0,
    top: 0,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.16)',
    borderWidth: 1,
    borderColor: 'rgba(219,234,254,0.24)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarSection: { alignItems: 'center', marginBottom: 18 },
  avatarPressable: { borderRadius: 59 },
  avatarPressed: { opacity: 0.92, transform: [{ scale: 0.98 }] },
  avatarRing: {
    width: 118,
    height: 118,
    borderRadius: 59,
    padding: 4,
    marginTop:24,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#60A5FA',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.22,
    shadowRadius: 20,
    elevation: 8,
  },
  avatarInner: {
    width: 110,
    height: 110,
    borderRadius: 55,
    backgroundColor: '#0F172A',
    overflow: 'hidden',
  },
  avatarImg: { width: '100%', height: '100%' },
  avatarFallback: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarInitial: {
    fontFamily: 'Inter_700Bold',
    fontSize: 38,
    color: '#FFFFFF',
  },
  activeDot: {
    position: 'absolute',
    bottom: 4,
    right: 4,
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#1D4ED8',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#DBEAFE',
    shadowColor: '#0F172A',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.18,
    shadowRadius: 12,
    elevation: 6,
  },
  heroName: {
    fontFamily: 'Inter_700Bold',
    fontSize: 28,
    color: '#F8FAFC',
    letterSpacing: -0.8,
    textAlign: 'center',
  },
  heroEmail: {
    fontFamily: 'Inter_400Regular',
    fontSize: 15,
    color: '#EFF6FF',
    marginTop: 8,
    textAlign: 'center',
    lineHeight: 22,
    maxWidth: '92%',
  },
  suspendedBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: 'rgba(127,29,29,0.32)',
    borderWidth: 1,
    borderColor: 'rgba(252,165,165,0.35)',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: radius.full,
    marginTop: 12,
  },
  suspendedText: { fontFamily: 'Inter_600SemiBold', fontSize: 11, color: '#FCA5A5' },
  statsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.16)',
    borderWidth: 1,
    borderColor: 'rgba(219,234,254,0.24)',
    borderRadius: 30,
    paddingVertical: 22,
    paddingHorizontal: 24,
    marginTop: 28,
    width: '100%',
  },
  statItem: { flex: 1, alignItems: 'center', gap: 6 },
  statValue: {
    fontFamily: 'Inter_700Bold',
    fontSize: 16,
    color: '#F1F5F9',
    letterSpacing: -0.5,
  },
  statLabel: {
    fontFamily: 'Inter_400Regular',
    fontSize: 12,
    color: '#E0F2FE',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  statDivider: { width: 1, height: 32, backgroundColor: 'rgba(255,255,255,0.18)' },
  body: {
    backgroundColor: 'rgba(248,251,255,0.97)',
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    paddingTop: 12,
    paddingBottom: 24,
    shadowColor: '#60A5FA',
    shadowOffset: { width: 0, height: -8 },
    shadowOpacity: 0.14,
    shadowRadius: 24,
    elevation: 16,
  },
  bodyGuest: {
    paddingTop: 0,
    paddingBottom: 0,
    flex: 1,
  },
  handle: {
    width: 40,
    height: 5,
    borderRadius: 3,
    backgroundColor: '#93C5FD',
    alignSelf: 'center',
    marginBottom: 24,
  },
  section: { paddingHorizontal: spacing.xl, marginBottom: 24 },
  sectionLabel: {
    fontFamily: 'Inter_700Bold',
    fontSize: 12,
    color: '#60A5FA',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    marginBottom: 12,
  },
  quickActions: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingRight: 4,
  },
  quickAction: {
    alignItems: 'center',
    gap: 8,
    width: 72,
  },
  quickActionSpacing: {
    marginRight: 12,
  },
  quickActionIcon: {
    width: 56,
    height: 56,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#DCEBFB',
    backgroundColor: '#FFFFFF',
  },
  quickActionLabel: {
    fontFamily: 'Inter_500Medium',
    fontSize: 12,
    color: '#334155',
  },
  infoCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#DCEBFB',
    overflow: 'hidden',
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: 14,
    gap: spacing.sm,
  },
  infoRowBorder: { borderBottomWidth: 1, borderBottomColor: '#EDF4FB' },
  infoIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: '#EFF6FF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoLabel: {
    fontFamily: 'Inter_500Medium',
    fontSize: 13,
    color: '#64748B',
    width: 92,
  },
  infoValue: {
    fontFamily: 'Inter_600SemiBold',
    fontSize: 13,
    color: '#0F172A',
    flex: 1,
    paddingLeft: 12,
    textAlign: 'right',
  },
  menuCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#DCEBFB',
    overflow: 'hidden',
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: 14,
    gap: spacing.sm,
  },
  menuItemPressed: { backgroundColor: '#F8FBFF' },
  menuItemBorder: { borderBottomWidth: 1, borderBottomColor: '#EDF4FB' },
  menuIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuTextWrap: { flex: 1, gap: 2 },
  menuLabel: {
    fontFamily: 'Inter_600SemiBold',
    fontSize: 14,
    color: '#0F172A',
  },
  menuSublabel: {
    fontFamily: 'Inter_400Regular',
    fontSize: 12,
    color: '#64748B',
  },
  signOutBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: spacing.xl,
    backgroundColor: '#FFF7F7',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#FECACA',
    paddingHorizontal: spacing.md,
    paddingVertical: 14,
    gap: spacing.sm,
    marginBottom: 16,
  },
  signOutIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: 'rgba(239,68,68,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  signOutText: {
    fontFamily: 'Inter_600SemiBold',
    fontSize: 14,
    color: '#EF4444',
    flex: 1,
  },
  versionText: {
    fontFamily: 'Inter_400Regular',
    fontSize: 12,
    color: '#64748B',
    textAlign: 'center',
    marginTop: 4,
  },
  guestSection: {
    flex: 1,
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.md,
    paddingBottom: spacing.lg,
    gap: spacing.md,
    justifyContent: 'space-between',
  },
  guestCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: radius.xl,
    paddingHorizontal: spacing.xl,
    paddingBottom: spacing.xl,
    paddingTop: spacing.md,
    overflow: 'hidden',
    gap: 12,
    borderWidth: 0,
    flex: 1,
    justifyContent: 'center',
  },
  guestCardTitle: {
    fontFamily: 'Inter_700Bold',
    fontSize: 18,
    color: '#0F172A',
    letterSpacing: -0.3,
  },
  guestCardSub: {
    fontFamily: 'Inter_400Regular',
    fontSize: 13,
    color: '#64748B',
    lineHeight: 20,
  },
  guestFeatures: { gap: 8 },
  guestFeatureRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  guestFeatureDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#0F1E3D',
  },
  guestFeatureText: {
    fontFamily: 'Inter_500Medium',
    fontSize: 13,
    color: '#334155',
  },
  guestSignInBtn: {
    borderRadius: radius.md,
    overflow: 'hidden',
    marginTop: 4,
    borderWidth: 1,
    borderColor: 'rgba(6,13,31,0.14)',
  },
  guestSignInGrad: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 52,
    gap: spacing.xs,
    backgroundColor: '#0F1E3D',
  },
  guestSignInText: {
    fontFamily: 'Inter_700Bold',
    fontSize: 15,
    color: '#FFFFFF',
    letterSpacing: 0.2,
  },
  exploreBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    borderWidth: 1,
    borderColor: '#DCEBFB',
    paddingHorizontal: spacing.md,
    paddingVertical: 14,
    gap: spacing.sm,
  },
  exploreBtnText: {
    fontFamily: 'Inter_600SemiBold',
    fontSize: 14,
    color: colors.primary,
    flex: 1,
  },
  previewOverlay: {
    flex: 1,
    backgroundColor: 'rgba(2,6,23,0.9)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.xl,
  },
  previewShell: {
    width: '100%',
    alignItems: 'center',
    gap: 18,
  },
  previewCloseBtn: {
    alignSelf: 'flex-end',
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: 'rgba(15,23,42,0.82)',
    borderWidth: 1,
    borderColor: 'rgba(148,163,184,0.24)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  previewPressed: { opacity: 0.85 },
  previewRing: {
    width: 280,
    height: 280,
    borderRadius: 140,
    padding: 6,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#60A5FA',
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.25,
    shadowRadius: 26,
    elevation: 12,
  },
  previewInner: {
    width: '100%',
    height: '100%',
    borderRadius: 134,
    overflow: 'hidden',
    backgroundColor: '#0F172A',
  },
  previewImage: { width: '100%', height: '100%' },
  previewFallback: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  previewInitial: {
    fontFamily: 'Inter_700Bold',
    fontSize: 92,
    color: '#FFFFFF',
  },
  previewName: {
    fontFamily: 'Inter_700Bold',
    fontSize: 20,
    color: '#F8FAFC',
    textAlign: 'center',
  },
});
